spring.application.name=twitter-clone
server.port=${PORT:3000}

#Datalar?m?z? environment olarak render'a ekledik o yüzden bunlar bu ?ekilde i?aretlendi.

#spring.datasource.url=${DATA_URL}
#spring.datasource.username=${DATA_USERNAME}
#spring.datasource.password=${DATA_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

#Vercel'deki frontend ile Render'daki backend farkl? adreslerde (Cross-Site)
#oldu?u için taray?c?n?n HTTPS üzerinden gönderilen JSESSIONID oturum çerezini güvenlik
#engeline tak?lmadan kaydedip saklamas?n? sa?lamak için eklendi.
#server.servlet.session.cookie.same-site=none
#server.servlet.session.cookie.secure=true